#!/usr/bin/env bash

: '
This script sets up the MoMA container and its supporting scripts.
It will use Singularity containers, when Singularity is present. It will try to use Docker otherwise.
It then calls the implementation of moma, which is copied from the container.
'

set -u

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source "${DIR}/setup_module.sh"

setup_module

### Start preprocessing with wrapper script
eval "${MOMA_BIN_DIRECTORY}/moma" "$@"
